# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dylanmichel/Desktop/Jeu3D/GLSL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dylanmichel/Desktop/Jeu3D/GLSL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dylanmichel/Desktop/Jeu3D/GLSL/CMakeFiles /Users/dylanmichel/Desktop/Jeu3D/GLSL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dylanmichel/Desktop/Jeu3D/GLSL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named 3D_Game_main

# Build rule for target.
3D_Game_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3D_Game_main
.PHONY : 3D_Game_main

# fast build rule for target.
3D_Game_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/build
.PHONY : 3D_Game_main/fast

#=============================================================================
# Target rules for targets named 3D_Game_test

# Build rule for target.
3D_Game_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3D_Game_test
.PHONY : 3D_Game_test

# fast build rule for target.
3D_Game_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/build
.PHONY : 3D_Game_test/fast

import/glad/src/glad.o: import/glad/src/glad.c.o
.PHONY : import/glad/src/glad.o

# target to build an object file
import/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/import/glad/src/glad.c.o
.PHONY : import/glad/src/glad.c.o

import/glad/src/glad.i: import/glad/src/glad.c.i
.PHONY : import/glad/src/glad.i

# target to preprocess a source file
import/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/import/glad/src/glad.c.i
.PHONY : import/glad/src/glad.c.i

import/glad/src/glad.s: import/glad/src/glad.c.s
.PHONY : import/glad/src/glad.s

# target to generate assembly for a file
import/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/import/glad/src/glad.c.s
.PHONY : import/glad/src/glad.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/main.cpp.s
.PHONY : main.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Camera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Camera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Camera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/EBO.o: src/EBO.cpp.o
.PHONY : src/EBO.o

# target to build an object file
src/EBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/EBO.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/EBO.cpp.o
.PHONY : src/EBO.cpp.o

src/EBO.i: src/EBO.cpp.i
.PHONY : src/EBO.i

# target to preprocess a source file
src/EBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/EBO.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/EBO.cpp.i
.PHONY : src/EBO.cpp.i

src/EBO.s: src/EBO.cpp.s
.PHONY : src/EBO.s

# target to generate assembly for a file
src/EBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/EBO.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/EBO.cpp.s
.PHONY : src/EBO.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Mesh.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Mesh.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Mesh.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Texture.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Texture.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/Texture.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/VAO.o: src/VAO.cpp.o
.PHONY : src/VAO.o

# target to build an object file
src/VAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/VAO.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/VAO.cpp.o
.PHONY : src/VAO.cpp.o

src/VAO.i: src/VAO.cpp.i
.PHONY : src/VAO.i

# target to preprocess a source file
src/VAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/VAO.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/VAO.cpp.i
.PHONY : src/VAO.cpp.i

src/VAO.s: src/VAO.cpp.s
.PHONY : src/VAO.s

# target to generate assembly for a file
src/VAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/VAO.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/VAO.cpp.s
.PHONY : src/VAO.cpp.s

src/VBO.o: src/VBO.cpp.o
.PHONY : src/VBO.o

# target to build an object file
src/VBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/VBO.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/VBO.cpp.o
.PHONY : src/VBO.cpp.o

src/VBO.i: src/VBO.cpp.i
.PHONY : src/VBO.i

# target to preprocess a source file
src/VBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/VBO.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/VBO.cpp.i
.PHONY : src/VBO.cpp.i

src/VBO.s: src/VBO.cpp.s
.PHONY : src/VBO.s

# target to generate assembly for a file
src/VBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/VBO.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/VBO.cpp.s
.PHONY : src/VBO.cpp.s

src/model.o: src/model.cpp.o
.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/model.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/model.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/model.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/shaderClass.o: src/shaderClass.cpp.o
.PHONY : src/shaderClass.o

# target to build an object file
src/shaderClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/shaderClass.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/shaderClass.cpp.o
.PHONY : src/shaderClass.cpp.o

src/shaderClass.i: src/shaderClass.cpp.i
.PHONY : src/shaderClass.i

# target to preprocess a source file
src/shaderClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/shaderClass.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/shaderClass.cpp.i
.PHONY : src/shaderClass.cpp.i

src/shaderClass.s: src/shaderClass.cpp.s
.PHONY : src/shaderClass.s

# target to generate assembly for a file
src/shaderClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_main.dir/build.make CMakeFiles/3D_Game_main.dir/src/shaderClass.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/src/shaderClass.cpp.s
.PHONY : src/shaderClass.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3D_Game_test.dir/build.make CMakeFiles/3D_Game_test.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 3D_Game_main"
	@echo "... 3D_Game_test"
	@echo "... glad"
	@echo "... import/glad/src/glad.o"
	@echo "... import/glad/src/glad.i"
	@echo "... import/glad/src/glad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/EBO.o"
	@echo "... src/EBO.i"
	@echo "... src/EBO.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/VAO.o"
	@echo "... src/VAO.i"
	@echo "... src/VAO.s"
	@echo "... src/VBO.o"
	@echo "... src/VBO.i"
	@echo "... src/VBO.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/shaderClass.o"
	@echo "... src/shaderClass.i"
	@echo "... src/shaderClass.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

